# Generated by Django 2.1.7 on 2019-02-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20190217_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(upload_to='static/issues/images'),
        ),
    ]
